spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.32.138:3306/msb_dongbao_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.32.138
    port: 6379
    timeout: 2000s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:
    classpath*:/com/msb/dongbao/ums/mapper/xml/*.xml
  type-aliases-package: com.msb.dongbao.ums.entity
kaptcha:
  height: 100
  width: 300
  content:
    length: 6
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: red
    name: Arial
    size: 40
  background-color:
    from: yellow
    to: green
  border:
    enabled: true
    color: black
    thickness: 1

